/* PHL Franchise Simulator — Season Awards
 * Global namespace: window.PHLAwards
 *
 * Separate from js/mvp.js's per-division MVP awards (First-Half,
 * Second-Half, Playoff Series). These are computed once per season, at
 * the same moment the Second-Half MVP is revealed — right as the regular
 * season ends and the playoffs begin (see js/calendar.js runRegularWeek)
 * — off each player's FULL season stat line, not a half-season diff:
 *
 *   - Defenseman of the Year (per division)
 *   - Goalie of the Year (per division)
 *   - Rookie of the Year (per division) — scoped to players generated by
 *     this season's breakout rookie class (see js/stats.js
 *     generateRookieClass, which stamps p.rookieSeason)
 *   - Player of the Year (one, league-wide)
 *
 * Rendered alongside the MVP awards on the Stats & Offseason > Awards tab
 * (see js/stats.js renderAwardsView).
 */
(function () {
  "use strict";
  var S = window.PHLState;

  function rosteredInDivision(divisionId) {
    var teamIds = S.getTeams(divisionId).map(function (t) { return t.id; });
    return S.getPlayers().filter(function (p) {
      return p.teamId && teamIds.indexOf(p.teamId) !== -1 && !p.retired;
    });
  }

  function pickBest(players, scoreFn) {
    var best = null;
    var bestScore = -Infinity;
    players.forEach(function (p) {
      var s = scoreFn(p);
      if (s > bestScore) {
        bestScore = s;
        best = p;
      }
    });
    return best;
  }

  function skaterScore(p) {
    var st = p.stats;
    if (!st || !st.gp) return -Infinity;
    return st.pts * 2 + (st.plusMinus || 0) * 0.5 + st.gp * 0.2;
  }
  // Leans harder on plus/minus (two-way value) than the general skater
  // score above — a Defenseman of the Year shouldn't just be "best offense
  // among defensemen".
  function defensemanScore(p) {
    var st = p.stats;
    if (!st || !st.gp) return -Infinity;
    return st.pts * 1.3 + (st.plusMinus || 0) * 1.2 + st.gp * 0.2;
  }
  function goalieScore(p) {
    var st = p.stats;
    if (!st || st.gp < 2) return -Infinity;
    return (st.svPct || 0) * 140 - (st.gaa || 0) * 8 + st.gp * 0.5;
  }
  function generalScore(p) {
    return p.position === "G" ? goalieScore(p) : skaterScore(p);
  }

  function notify(title, body, teamId) {
    if (window.PHLInbox && S.isUserRelevantTeam(teamId)) {
      window.PHLInbox.addNotification({ type: "award", title: title, body: body });
    }
  }

  function computeSeasonAwards() {
    var season = S.getSeason();
    var seasonNumber = season.seasonNumber;
    var awarded = [];

    S.getDivisions().forEach(function (div) {
      var players = rosteredInDivision(div.id);
      var divName = (S.getDivision(div.id) || {}).name;

      var defensemen = players.filter(function (p) { return p.position === "D"; });
      var doty = pickBest(defensemen, defensemanScore);
      if (doty) {
        S.addSeasonAward({ season: seasonNumber, divisionId: div.id, type: "defenseman", playerId: doty.id });
        notify(divName + " Defenseman of the Year", doty.name + " has been named Defenseman of the Year for the " + divName + " Division!", doty.teamId);
        awarded.push(doty);
      }

      var goalies = players.filter(function (p) { return p.position === "G"; });
      var goty = pickBest(goalies, goalieScore);
      if (goty) {
        S.addSeasonAward({ season: seasonNumber, divisionId: div.id, type: "goalie", playerId: goty.id });
        notify(divName + " Goalie of the Year", goty.name + " has been named Goalie of the Year for the " + divName + " Division!", goty.teamId);
        awarded.push(goty);
      }

      var rookies = players.filter(function (p) { return p.rookieSeason === seasonNumber; });
      var roty = pickBest(rookies, generalScore);
      if (roty) {
        S.addSeasonAward({ season: seasonNumber, divisionId: div.id, type: "rookie", playerId: roty.id });
        notify(divName + " Rookie of the Year", roty.name + " has been named Rookie of the Year for the " + divName + " Division!", roty.teamId);
        awarded.push(roty);
      }
    });

    // League-wide Player of the Year — one award, best of everyone,
    // position-agnostic (a great goalie season can win it just as easily
    // as a great skater season).
    var everyone = S.getPlayers().filter(function (p) { return p.teamId && !p.retired; });
    var poty = pickBest(everyone, generalScore);
    if (poty) {
      S.addSeasonAward({ season: seasonNumber, divisionId: null, type: "player-of-the-year", playerId: poty.id });
      notify("League Player of the Year", poty.name + " has been named the PHL's Player of the Year!", poty.teamId);
      awarded.push(poty);
    }

    return awarded;
  }

  window.PHLAwards = {
    computeSeasonAwards: computeSeasonAwards,
  };
})();
